{"errorMessage": "An error occurred (ResourceNotFoundException) when calling the DescribeEntity operation: Requested entity 'blank' does not exist.", "errorType": "ResourceNotFoundException", "stackTrace": ["  File \"/var/task/lambda_function.py\", line 156, in lambda_handler\n    Catalog='AWSMarketplace', EntityId=product_id)\n", "  File \"/var/runtime/botocore/client.py\", line 357, in _api_call\n    return self._make_api_call(operation_name, kwargs)\n", "  File \"/var/runtime/botocore/client.py\", line 676, in _make_api_call\n    raise error_class(parsed_response, operation_name)\n"]}